service: ping-service

provider:
  name: aws
  runtime: python3.8
  environment:
    PYTHONPATH: /var/task/src:/opt/python
  memorySize: 256
  apiKeys:
    - abracadabra

plugins:
  - serverless-python-requirements

package:
  exclude:
    - "**/*"
  include:
    - '!.**'
    - src/**

functions:
  ping:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: post
          private: true
