service: pong-service

provider:
  name: aws
  runtime: python3.8
  deploymentBucket:
    name: ${cf:ping-service-${opt:stage}.ServerlessDeploymentBucketName}
  environment:
    PYTHONPATH: /var/task/src:/opt/python
  iamRoleStatements:
    - 

plugins:
  - serverless-python-requirements

package:
  exclude:
    - "**/*"
  include:
    - '!.**'
    - src/**

functions:
  pong:
    handler: src/index.handler
